export const CALL_TYPE_CALLOUT = 'CALL_TYPE_CALLOUT';
export const CALL_TYPE_CALLIN = 'CALL_TYPE_CALLIN';

export const CALL_STATUS_CALLOUT_INITIAL_UNKNOWN = 0;
export const CALL_STATUS_CALLOUT_INITIAL_BUSY = -3;
export const CALL_STATUS_CALLOUT_INITIAL_NOT_ENOUGH_BALANCE = -4;
export const CALL_STATUS_CALLOUT_INITIAL_INVALID_NUMBER = -5;
export const CALL_STATUS_CALLOUT_STATUS_UNKNOWN = 0;
export const CALL_STATUS_CALLOUT_STATUS_CONNECTING = 100;
export const CALL_STATUS_CALLOUT_STATUS_RINGING = 183;
export const CALL_STATUS_CALLOUT_STATUS_ANSWERED = 200;
export const CALL_STATUS_CALLOUT_STATUS_BUSY = 486;
export const CALL_STATUS_CALLOUT_STATUS_NOT_ANSWERED = 480;
export const CALL_STATUS_CALLOUT_STATUS_STOP = 700;
export const CALL_STATUS_CALLOUT_STATUS_NOT_ENOUGH_BALANCE = 702;

export const CALL_STATUS_CALLIN_STATUS_UNKNOWN = 0;
export const CALL_STATUS_CALLIN_STATUS_RINGING = 183;
export const CALL_STATUS_CALLIN_STATUS_ANSWERED = 200;
export const CALL_STATUS_CALLIN_STATUS_BUSY = 486;
export const CALL_STATUS_CALLIN_STATUS_NOT_ANSWERED = 403;
export const CALL_STATUS_CALLIN_STATUS_RINGING_STOP = 702;
export const CALL_STATUS_CALLIN_STATUS_STOP = 700;

export const CALL_PAID_LOG_CALL_TYPE_CALLOUT = 1;
export const CALL_PAID_LOG_CALL_TYPE_CALLIN = 2;
export const CALL_PAID_LOG_CALL_STATUS_ANSWERED = 0;
export const CALL_PAID_LOG_CALL_STATUS_REJECTED = 1;
export const CALL_PAID_LOG_CALL_STATUS_NOT_ANSWERED = 2;