export const CALL_TYPE_CALLOUT = 'CALL_TYPE_CALLOUT';

export const CALL_STATUS_CALLOUT_BUSY = -3;
export const CALL_STATUS_CALLOUT_NOT_ENOUGH_BALANCE = -4;
export const CALL_STATUS_CALLOUT_INVALID_NUMBER = -5;