export const CHAT_TYPE_FROM_SERVER_UNKNOWN = 0;
export const CHAT_TYPE_FROM_SERVER_USER = 1;
export const CHAT_TYPE_FROM_SERVER_GROUP = 2;
export const CHAT_TYPE_UNKNOWN = 'CHAT_TYPE_UNKNOWN';
export const CHAT_TYPE_USER = 'CHAT_TYPE_USER';
export const CHAT_TYPE_GROUP = 'CHAT_TYPE_GROUP';