export const ERR_SOCKET_CONNECT = 'ERR_SOCKET_CONNECT';
export const ERR_SOCKET_PARSE_BODY = 'ERR_SOCKET_PARSE_BODY';
export const ERR_SOCKET_UNKNOWN_SERVICE = 'ERR_SOCKET_UNKNOWN_SERVICE';
export const ERR_SOCKET_REQUEST_TIME_OUT = 'ERR_SOCKET_REQUEST_TIME_OUT';

export const ERR_UNEXPECTED_SEND_DATA = 'ERR_UNEXPECTED_SEND_DATA';
export const ERR_UNEXPECTED_RECEIVED_DATA = 'ERR_UNEXPECTED_RECEIVED_DATA';