export const REQUEST_SUCCESS_FROM_SERVER = 1;
export const CHANGE_STATUS_MESSAGE_SUCCESS_FROM_SERVER = 0;
export const DELETE_MESSAGE_SUCCESS_FROM_SERVER = 0;
export const GROUP_INVITE_SUCCESS_FROM_SERVER = 0;
export const GROUP_LEAVE_SUCCESS_FROM_SERVER = 0;
export const GROUP_RENAME_SUCCESS_FROM_SERVER = 0;

export const ERR_SOCKET_CONNECT = 'ERR_SOCKET_CONNECT';
export const ERR_SOCKET_PARSE_BODY = 'ERR_SOCKET_PARSE_BODY';
export const ERR_SOCKET_UNKNOWN_SERVICE = 'ERR_SOCKET_UNKNOWN_SERVICE';
export const ERR_SOCKET_NOT_CONNECTED = 'ERR_SOCKET_NOT_CONNECTED';

export const ERR_REQUEST_TIMEOUT = 'ERR_REQUEST_TIMEOUT';

export const ERR_UNEXPECTED_DATA = 'ERR_UNEXPECTED_DATA';
export const ERR_UNEXPECTED_SEND_DATA = 'ERR_UNEXPECTED_SEND_DATA';
export const ERR_UNEXPECTED_RECEIVED_DATA = 'ERR_UNEXPECTED_RECEIVED_DATA';

export const ERR_WEBRTC = 'ERR_WEBRTC';