export const AUTHENTICATION_GET_SERVER_ADDR = 29;
export const AUTHENTICATION_SEND_AUTHENTICATE = 179;
export const AUTHENTICATION_RECEIVE_AUTHENTICATE = 162;

export const CALLOUT_START_SEND = 500;
export const CALLOUT_START_SUCCESS = 504;
export const CALLOUT_START_ERROR = 610;