export const UNCALL_TEMPORARY_TYPE_ARRAY = 'UNCALL_TEMPORARY_TYPE_ARRAY';

export const UNCALL_KEY_AUTHENTICATION = 'UNCALL_KEY_AUTHENTICATION';
export const UNCALL_KEY_DISCONNECT = 'UNCALL_KEY_DISCONNECT';
export const UNCALL_KEY_TOGGLE_AUDIO_STATE = 'UNCALL_KEY_TOGGLE_AUDIO_STATE';
export const UNCALL_KEY_START_CALLOUT = 'UNCALL_KEY_START_CALLOUT';
export const UNCALL_KEY_STOP_CALLOUT = 'UNCALL_KEY_STOP_CALLOUT';
export const UNCALL_KEY_ANSWER_CALLIN = 'UNCALL_KEY_ANSWER_CALLIN';
export const UNCALL_KEY_REJECT_CALLIN = 'UNCALL_KEY_REJECT_CALLIN';
export const UNCALL_KEY_NOT_ANSWERED_CALLIN = 'UNCALL_KEY_NOT_ANSWERED_CALLIN';
export const UNCALL_KEY_STOP_CALLIN = 'UNCALL_KEY_STOP_CALLIN';
export const UNCALL_KEY_GET_PAID_CALL_LOGS = 'UNCALL_KEY_GET_PAID_CALL_LOGS';
export const UNCALL_KEY_GET_UNREAD_MESSAGES = 'UNCALL_KEY_GET_UNREAD_MESSAGES';
export const UNCALL_KEY_GET_MODIFIED_MESSAGES = 'UNCALL_KEY_GET_MODIFIED_MESSAGES';
export const UNCALL_KEY_GET_USERS_INFORMATION = 'UNCALL_KEY_GET_USERS_INFORMATION';