export const EVENT_NAME_CONNECT_RETURN = 'EVENT_NAME_CONNECT_RETURN';
export const EVENT_NAME_ON_AUTO_RECONNECT_START = 'EVENT_NAME_ON_AUTO_RECONNECT_START';
export const EVENT_NAME_ON_AUTO_RECONNECT_STOP = 'EVENT_NAME_ON_AUTO_RECONNECT_STOP';
export const EVENT_NAME_ON_AUTO_RECONNECTED = 'EVENT_NAME_ON_AUTO_RECONNECTED';
export const EVENT_NAME_ON_RECONNECT_RETURN = 'EVENT_NAME_ON_RECONNECT_RETURN';
export const EVENT_NAME_ON_DISCONNECTED = 'EVENT_NAME_ON_DISCONNECTED';
export const EVENT_NAME_ON_DISCONNECT_RETURN = 'EVENT_NAME_ON_DISCONNECT_RETURN';

export const EVENT_NAME_ON_MESSAGE_LIST_SCROLL_START = 'EVENT_NAME_ON_MESSAGE_LIST_SCROLL_START';
export const EVENT_NAME_ON_MESSAGE_DETAILS_SHOWED = 'EVENT_NAME_ON_MESSAGE_DETAILS_SHOWED';
export const EVENT_NAME_ON_MESSAGE_MEDIA_PLAYED = 'EVENT_NAME_ON_MESSAGE_MEDIA_PLAYED';
export const EVENT_NAME_ON_STICKER_PACKET_DOWNLOAD_STATUS_CHANGED = 'EVENT_NAME_ON_STICKER_PACKET_DOWNLOAD_STATUS_CHANGED';

// callin
export const EVENT_NAME_CALLIN_START = 'EVENT_NAME_CALLIN_START';
export const EVENT_NAME_CALLIN_STATUS_CHANGED = 'EVENT_NAME_CALLIN_STATUS_CHANGED';
export const EVENT_NAME_CALLIN_STATUS_CHANGED_BY_ME = 'EVENT_NAME_CALLIN_STATUS_CHANGED_BY_ME';

// callout
export const EVENT_NAME_CALLOUT_STATUS_CHANGED = 'EVENT_NAME_CALLOUT_STATUS_CHANGED';
export const EVENT_NAME_CALLOUT_START_RETURN = 'EVENT_NAME_CALLOUT_START_RETURN';

// typing
export const EVENT_NAME_ON_TYPING = 'EVENT_NAME_ON_TYPING';

// message events
export const EVENT_NAME_ON_MESSAGE_STATUS_CHANGED = 'EVENT_NAME_ON_MESSAGE_STATUS_CHANGED';
export const EVENT_NAME_ON_NEW_MESSAGE = 'EVENT_NAME_ON_NEW_MESSAGE';
export const EVENT_NAME_ON_MESSAGE_FROM_ME = 'EVENT_NAME_ON_MESSAGE_FROM_ME';
export const EVENT_NAME_ON_NEW_MESSAGE_RETURN = 'EVENT_NAME_ON_NEW_MESSAGE_RETURN';

// group events
export const EVENT_NAME_ON_GROUP_CREATED = 'EVENT_NAME_ON_GROUP_CREATED';
export const EVENT_NAME_ON_GROUP_INVITED = 'EVENT_NAME_ON_GROUP_INVITED';
export const EVENT_NAME_ON_GROUP_LEFT = 'EVENT_NAME_ON_GROUP_LEFT';
export const EVENT_NAME_ON_GROUP_RENAMED = 'EVENT_NAME_ON_GROUP_RENAMED';
export const EVENT_NAME_ON_GROUP_ADMIN_CHANGED = 'EVENT_NAME_ON_GROUP_ADMIN_CHANGED';
export const EVENT_NAME_ON_GROUP_PUBLIC_JOINED = 'EVENT_NAME_ON_GROUP_PUBLIC_JOINED';

// free call
export const EVENT_NAME_FREE_CALL_START = 'EVENT_NAME_FREE_CALL_START';
export const EVENT_NAME_FREE_CALL_STATUS_CHANGED = 'EVENT_NAME_FREE_CALL_STATUS_CHANGED';
export const EVENT_NAME_FREE_CALL_STATUS_CHANGED_BY_ME = 'EVENT_NAME_FREE_CALL_STATUS_CHANGED_BY_ME';
export const EVENT_NAME_LOCAL_STREAM_ARRIVED = 'EVENT_NAME_LOCAL_STREAM_ARRIVED';
export const EVENT_NAME_REMOTE_STREAM_ARRIVED = 'EVENT_NAME_REMOTE_STREAM_ARRIVED';
export const EVENT_NAME_SWITCH_CAMERA_TYPE_RETURN = 'EVENT_NAME_SWITCH_CAMERA_TYPE_RETURN';

// call log (paid call logs)
export const EVENT_NAME_PAID_CALL_LOG_RETURN = 'EVENT_NAME_PAID_CALL_LOG_RETURN';