export const DATA_TYPE_STRING = 'DATA_TYPE_STRING';
export const DATA_TYPE_NUMBER = 'DATA_TYPE_NUMBER';
export const DATA_TYPE_BOOLEAN = 'DATA_TYPE_BOOLEAN';
export const DATA_TYPE_PHONE_NUMBER = 'DATA_TYPE_PHONE_NUMBER';
export const DATA_TYPE_URL = 'DATA_TYPE_URL';
export const DATA_TYPE_ARRAY = 'DATA_TYPE_ARRAY';
export const DATA_TYPE_OBJECT = 'DATA_TYPE_OBJECT';
