export const STICKER_TYPE_DEFAULT = 1;
export const STICKER_TYPE_NOT_DEFAULT = 0;

export const STICKER_DEFAULT_CATID_2_ORIGINAL = 2; 
export const STICKER_DEFAULT_CATID_2_FAKE = 12; 
export const STICKER_DEFAULT_CATID_3_ORIGINAL = 3; 
export const STICKER_DEFAULT_CATID_3_FAKE = 13; 
export const STICKER_DEFAULT_CATID_4_ORIGINAL = 4; 
export const STICKER_DEFAULT_CATID_4_FAKE = 15; 
export const STICKER_DEFAULT_CATID_5_ORIGINAL = 5; 
export const STICKER_DEFAULT_CATID_5_FAKE = 16; 