export const UNCALL_TEMPORARY_TYPE_ARRAY = 'UNCALL_TEMPORARY_TYPE_ARRAY';
export const UNCALL_TEMPORARY_TYPE_OBJECT = 'UNCALL_TEMPORARY_TYPE_OBJECT';


export const UNCALL_KEY_CONNECT = 'UNCALL_KEY_CONNECT';
export const UNCALL_KEY_RECONNECT = 'UNCALL_KEY_RECONNECT';
export const UNCALL_KEY_DISCONNECT = 'UNCALL_KEY_DISCONNECT';

export const UNCALL_KEY_TOGGLE_AUDIO_STATE = 'UNCALL_KEY_TOGGLE_AUDIO_STATE';
export const UNCALL_KEY_TOGGLE_VIDEO_STATE = 'UNCALL_KEY_TOGGLE_VIDEO_STATE';
export const UNCALL_KEY_SWITCH_CAMERA_TYPE = 'UNCALL_KEY_SWITCH_CAMERA_TYPE';

export const UNCALL_KEY_START_FREE_CALL = 'UNCALL_KEY_START_FREE_CALL';
export const UNCALL_KEY_STOP_FREE_CALL = 'UNCALL_KEY_STOP_FREE_CALL';
export const UNCALL_KEY_ANSWER_FREE_CALL = 'UNCALL_KEY_ANSWER_FREE_CALL';
export const UNCALL_KEY_REJECT_FREE_CALL = 'UNCALL_KEY_REJECT_FREE_CALL';
export const UNCALL_KEY_NOT_ANSWER_FREE_CALL = 'UNCALL_KEY_NOT_ANSWER_FREE_CALL';

export const UNCALL_KEY_START_CALLOUT = 'UNCALL_KEY_START_CALLOUT';
export const UNCALL_KEY_STOP_CALLOUT = 'UNCALL_KEY_STOP_CALLOUT';

export const UNCALL_KEY_ANSWER_CALLIN = 'UNCALL_KEY_ANSWER_CALLIN';
export const UNCALL_KEY_REJECT_CALLIN = 'UNCALL_KEY_REJECT_CALLIN';
export const UNCALL_KEY_NOT_ANSWERED_CALLIN = 'UNCALL_KEY_NOT_ANSWERED_CALLIN';
export const UNCALL_KEY_STOP_CALLIN = 'UNCALL_KEY_STOP_CALLIN';

export const UNCALL_KEY_GET_PAID_CALL_LOGS = 'UNCALL_KEY_GET_PAID_CALL_LOGS';

export const UNCALL_KEY_GET_MODIFIED_CONVERSATIONS = 'UNCALL_KEY_GET_MODIFIED_CONVERSATIONS';

export const UNCALL_KEY_DELETE_CONVERSATION = 'UNCALL_KEY_DELETE_CONVERSATION';

export const UNCALL_KEY_GET_UNREAD_MESSAGES = 'UNCALL_KEY_GET_UNREAD_MESSAGES';
export const UNCALL_KEY_GET_MODIFIED_MESSAGES = 'UNCALL_KEY_GET_MODIFIED_MESSAGES';
export const UNCALL_KEY_GET_MODIFIED_FILES = 'UNCALL_KEY_GET_MODIFIED_FILES';

export const UNCALL_KEY_NEW_MESSAGE = 'UNCALL_KEY_NEW_MESSAGE';

export const UNCALL_KEY_CHANGE_MESSAGE_STATUS = 'UNCALL_KEY_CHANGE_MESSAGE_STATUS';

export const UNCALL_KEY_DELETE_MESSAGE = 'UNCALL_KEY_DELETE_MESSAGE';

export const UNCALL_KEY_SEND_TYPING = 'UNCALL_KEY_SEND_TYPING';

export const UNCALL_KEY_GET_USERS_INFORMATION = 'UNCALL_KEY_GET_USERS_INFORMATION';

export const UNCALL_KEY_GROUP_CREATE = 'UNCALL_KEY_GROUP_CREATE';
export const UNCALL_KEY_GROUP_INVITE = 'UNCALL_KEY_GROUP_INVITE';
export const UNCALL_KEY_GROUP_LEAVE = 'UNCALL_KEY_GROUP_LEAVE';
export const UNCALL_KEY_GROUP_RENAME = 'UNCALL_KEY_GROUP_RENAME';
export const UNCALL_KEY_GROUP_CHANGE_ADMIN = 'UNCALL_KEY_GROUP_CHANGE_ADMIN';
export const UNCALL_KEY_GROUP_JOIN_PUBLIC = 'UNCALL_KEY_GROUP_JOIN_PUBLIC';

export const UNCALL_KEY_GROUP_GET_DETAILS = 'UNCALL_KEY_GROUP_GET_DETAILS';
export const UNCALL_KEY_GROUP_GET_LIST = 'UNCALL_KEY_GROUP_GET_LIST';

export const UNCALL_KEY_APPLICATION_CHANGE_STATE = 'UNCALL_KEY_APPLICATION_CHANGE_STATE';

export const UNCALL_KEY_NOTIFICATION_REGISTER_DEVICE = 'UNCALL_KEY_NOTIFICATION_REGISTER_DEVICE';
export const UNCALL_KEY_NOTIFICATION_PARSE = 'UNCALL_KEY_NOTIFICATION_PARSE';

export const UNCALL_KEY_GET_STICKERS_LIST = 'UNCALL_KEY_GET_STICKERS_LIST';
